### ISSUE TITLE
[BUG] Bot accounts work for a bit then crash when trying to type and send a message as well as unable to select a channel

### ISSUE THREAD

**Issue by 9xN** [MyPasswordIsWeak/cli-cord#16]
![Screen Shot 2021-11-23 at 11 07 44 PM](https://user-images.githubusercontent.com/94141577/143184049-31d8f20e-b1bb-46f7-a0bd-6e7a8fb49f74.png)

**Comment by 9xN** [comment]
[23:02:48][GENERIC][REJECTION] === ERROR ===
[23:02:51][INIT] Loaded default theme
[23:02:51][INIT] Dependency versions: -- blessed@0.1.81, cli-core@7c303d701778da53fcaca424a1c75251f12942a6, node-fetch@2.6.6, tr46@0.0.3, webidl-conversions@3.0.1, whatwg-url@5.0.0, ws@7.5.5 --
[23:02:51][INIT] Cli-core versions: -- package.json: 0.2.0 -- git: f568bb5dd5409a875d47894c37bf76cdc38a184c --
[23:02:56][INIT][KEYS] Done starting input
[23:02:56][CLI-CORE] Discord client is ready
[23:04:46][GENERIC][REJECTION] === ERROR ===
[23:04:46][GENERIC][REJECTION] Name: TypeError
[23:04:46][GENERIC][REJECTION] Message: Cannot read property 'id' of undefined
[23:04:46][GENERIC][REJECTION] Stacktrace: TypeError: Cannot read property 'id' of undefined
[23:04:46][GENERIC][REJECTION]    |    at BlessedList.<anonymous> (/Users/atg/cli-cord/source/views/messages.js:71:55)
[23:04:46][GENERIC][REJECTION]    |    at BlessedList.EventEmitter._emit (/Users/atg/cli-cord/node_modules/blessed/lib/events.js:94:20)
[23:04:46][GENERIC][REJECTION]    |    at BlessedList.EventEmitter.emit (/Users/atg/cli-cord/node_modules/blessed/lib/events.js:117:12)
[23:04:46][GENERIC][REJECTION]    |    at BlessedList.<anonymous> (/Users/atg/cli-cord/source/utils/blessed.js:205:11)
[23:04:46][GENERIC][REJECTION]    |    at BlessedList.EventEmitter._emit (/Users/atg/cli-cord/node_modules/blessed/lib/events.js:98:20)
[23:04:46][GENERIC][REJECTION]    |    at BlessedList.EventEmitter.emit (/Users/atg/cli-cord/node_modules/blessed/lib/events.js:117:12)
[23:04:46][GENERIC][REJECTION]    |    at Program.<anonymous> (/Users/atg/cli-cord/node_modules/blessed/lib/widgets/screen.js:602:15)
[23:04:46][GENERIC][REJECTION]    |    at Program.emit (events.js:314:20)
[23:04:46][GENERIC][REJECTION]    |    at /Users/atg/cli-cord/node_modules/blessed/lib/program.js:410:15
[23:04:46][GENERIC][REJECTION]    |    at Array.forEach (<anonymous>)
[23:04:46][GENERIC][REJECTION] === ERROR ===
[23:04:50][INIT] Loaded default theme
[23:04:50][INIT] Dependency versions: -- blessed@0.1.81, cli-core@7c303d701778da53fcaca424a1c75251f12942a6, node-fetch@2.6.6, tr46@0.0.3, webidl-conversions@3.0.1, whatwg-url@5.0.0, ws@7.5.5 --
[23:04:50][INIT] Cli-core versions: -- package.json: 0.2.0 -- git: f568bb5dd5409a875d47894c37bf76cdc38a184c --
[23:04:52][INIT][KEYS] Done starting input
[23:04:52][CLI-CORE] Discord client is ready

**Comment by MyPasswordIsWeak** [comment]
Fixed it in `81348337d01dd769e76a895a2ba3bd6a70e255b3`. PS: The bug would occur when pressing enter when nothing was selected, i wasn't checking if anything was selected if the user pressed enter but just hoping something was

**Comment by 9xN** [comment]
> Fixed it in `81348337d01dd769e76a895a2ba3bd6a70e255b3`. PS: The bug would occur when pressing enter when nothing was selected, i wasn't checking if anything was selected if the user pressed enter but just hoping something was

ah perfect
